"""empty message

Revision ID: 43e3bd227d89
Revises: 1ac71046e877
Create Date: 2017-01-25 11:50:32.353182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43e3bd227d89'
down_revision = '1ac71046e877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('state', sa.String(length=60), nullable=True))
    op.drop_column('address', 'country')
    op.add_column('company', sa.Column('website', sa.String(length=64), nullable=True))
    op.drop_column('company', 'Website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('Website', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('company', 'website')
    op.add_column('address', sa.Column('country', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('address', 'state')
    # ### end Alembic commands ###
