"""empty message

Revision ID: 81d86e8aa2b7
Revises: 4cf896915ace
Create Date: 2017-01-24 13:42:26.676371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d86e8aa2b7'
down_revision = '4cf896915ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=64), nullable=True),
    sa.Column('Website', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'employee', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column(u'employee', 'company_id')
    op.drop_table('company')
    # ### end Alembic commands ###
