"""empty message

Revision ID: 9ab9acd96f6f
Revises: 
Create Date: 2017-01-21 12:37:11.723070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab9acd96f6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workStation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('GPU', sa.Integer(), nullable=True),
    sa.Column('RAM', sa.Integer(), nullable=True),
    sa.Column('Disk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Requirement', sa.String(length=64), nullable=True),
    sa.Column('workStation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workStation_id'], ['workStation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('names', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_eng', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('social_id', sa.String(length=64), nullable=True),
    sa.Column('adress', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('validate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['validate_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adress'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_names'), 'employee', ['names'], unique=False)
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=True)
    op.create_table('Working_on',
    sa.Column('Eng_id', sa.Integer(), nullable=True),
    sa.Column('Order_id', sa.Integer(), nullable=True),
    sa.Column('Start_Date', sa.Date(), nullable=True),
    sa.Column('End_Date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Eng_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['Order_id'], ['order.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Working_on')
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_index(op.f('ix_employee_names'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('order')
    op.drop_table('workStation')
    # ### end Alembic commands ###
